### PR TITLE
TotalSupply

### PR DESCRIPTION
**Pull request by gawainb**
Updated subgraph to include TotalSupply.

We would like to use the TotalSupply function from the contract ABI to add logic that will create strategies for POAP weight voting.

### CODE REVIEW

**Review by alavarello — COMMENTED** [review]
Hi! Thanks for the PR.

I don't understand what's the difference between the new `event.totalSupply` and `event.tokenCount`

Please vertically align the operators
```
variable1    = 1;
longVariable = 1;
```

**Comment by gawainb** [comment]
> Hi! Thanks for the PR.
> 
> I don't understand what's the difference between the new `event.totalSupply` and `event.tokenCount`
> 
> Please vertically align the operators
> ```
> variable1    = 1;
> longVariable = 1;
> ```

Ahhh ok is that what tokenCount is for. I guess I was just following Documentation maybe is missed that.

**Comment by alavarello** [comment]
> > Hi! Thanks for the PR.
> > I don't understand what's the difference between the new `event.totalSupply` and `event.tokenCount`
> > Please vertically align the operators
> > ```
> > variable1    = 1;
> > longVariable = 1;
> > ```
> 
> Ahhh ok is that what tokenCount is for. I guess I was just following Documentation maybe is missed that.

Yes, we use `tokenCount` for that. 
Also the `token.totalSupply` should be always one. We don't mint copies for a token.

**Comment by alavarello** [comment]
Closing this PR. The info added with `token.totalSupply` and `event.totalSupply` it's not necessary

**Pull request closed without merging**
